// File: ROMO.v
// Generated by MyHDL 0.9dev
// Date: Sat Nov  1 11:32:35 2014


`timescale 1ns/10ps

module ROMO (
    addr,
    clk,
    datao
);


input [5:0] addr;
input clk;
output [13:0] datao;
reg [13:0] datao;






always @(posedge clk) begin: ROMO_RTL
    case (addr)
        0: datao <= 0;
        1: datao <= 400;
        2: datao <= 1138;
        3: datao <= 1538;
        4: datao <= 1703;
        5: datao <= 2103;
        6: datao <= 2841;
        7: datao <= 3241;
        8: datao <= 2009;
        9: datao <= 2409;
        10: datao <= 3147;
        11: datao <= 3547;
        12: datao <= 3712;
        13: datao <= 4112;
        14: datao <= 4850;
        15: datao <= 5250;
        16: datao <= 0;
        17: datao <= (-1138);
        18: datao <= (-2009);
        19: datao <= (-3147);
        20: datao <= (-400);
        21: datao <= (-1538);
        22: datao <= (-2409);
        23: datao <= (-3547);
        24: datao <= 1703;
        25: datao <= 565;
        26: datao <= (-306);
        27: datao <= (-1444);
        28: datao <= 1303;
        29: datao <= 165;
        30: datao <= (-706);
        31: datao <= (-1844);
        32: datao <= 0;
        33: datao <= 1703;
        34: datao <= 400;
        35: datao <= 2103;
        36: datao <= (-2009);
        37: datao <= (-306);
        38: datao <= (-1609);
        39: datao <= 94;
        40: datao <= 1138;
        41: datao <= 2841;
        42: datao <= 1538;
        43: datao <= 3241;
        44: datao <= (-871);
        45: datao <= 832;
        46: datao <= (-471);
        47: datao <= 1232;
        48: datao <= 0;
        49: datao <= (-2009);
        50: datao <= 1703;
        51: datao <= (-306);
        52: datao <= (-1138);
        53: datao <= (-3147);
        54: datao <= 871;
        55: datao <= (-1444);
        56: datao <= 400;
        57: datao <= (-1609);
        58: datao <= 2103;
        59: datao <= 94;
        60: datao <= (-738);
        61: datao <= (-2747);
        62: datao <= 965;
        default: datao <= (-1044);
    endcase
end

endmodule
