#ifndef __HW_EXTRA_FLAGS_H
#define __HW_EXTRA_FLAGS_H

#define DVISAMPLER_DELAY_RST		0x01
#define DVISAMPLER_DELAY_MASTER_INC	0x02
#define DVISAMPLER_DELAY_MASTER_DEC	0x04
#define DVISAMPLER_DELAY_SLAVE_INC	0x08
#define DVISAMPLER_DELAY_SLAVE_DEC	0x10

#endif /* __HW_FLAGS_H */
